version: '3.3'
services:
  api:
    build:
      context: .
      dockerfile: api-Dockerfile
    command: npm run start:server
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3333:3333"
