# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master,feature/*,develop]
  pull_request:
    branches: [ master,develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it
      - name: add mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
          mysql user: 'dev' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: 'mysql' # Required if "mysql user" exists. The password for the "mysql user"
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Cache node modules0
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test landingpage
        run: npm run test landingpage
      - name: Test api
        if: github.ref == 'refs/heads/master'
        run: npm run test api
      - name: Build
        run: npm run build
      - name: Build Api
        if: github.ref == 'refs/heads/master'
        run: npm run build:api
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            dist/apps/landingpage s3://despairdrivendevelopment.net
