# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master,feature/*,develop]
  pull_request:
    branches: [ master,develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Cache node modules0
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Build Api
        run: npm run build:api
      - name: add package.json and locks in api build
        run: cp ./package*.json yarn* ./dist/apps/api
      - name: add docker related files to build dir
        run: cp api-Dockerfile api-docker-compose.yml ./dist/apps/api
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            dist/apps/landingpage s3://despairdrivendevelopment.net
      - name: send api build to remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./dist/apps/api
          remote: api
          host: ${{secrets.api_host}}
          username: ${{secrets.api_host_user}}
          privateKey: ${{ secrets.SSH_DEPLOYMENT_KEY }}
          recursive: true
      - name: Deploy api server
        uses: appleboy/ssh-action@master
        with:
          username: ${{secrets.api_host_user}}
          host: ${{secrets.api_host}}
          key: ${{ secrets.SSH_DEPLOYMENT_KEY }}
          script: |
            runContainer () {
            sudo docker-compose -f api-docker-compose.yml up -d
            }
            checkIfDockerIsInstalled () {
            sudo docker -v
            dockerIsInstalled=$?
            docker-compose -v
            if [[ $? != 0 || $dockerIsInstalled != 0 ]]
            then
            sudo apt-get update
            sudo apt-get remove docker docker-engine docker.io
            sudo apt install docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            sudo docker-compose --version
             fi
             }
            cd api
            checkIfDockerIsInstalled;
            runContainer;
